### PR TITLE
Add support for TF resources

### PR DESCRIPTION
**Pull request by SvenW**
I've added support for Terraform resources

### CODE REVIEW

**Review by laszlocph — APPROVED** [review]

**Comment by sebastiangaiser** [comment]
@SvenW @laszlocph thank you for implementing this feature. After upgrading to v0.4.4 I got the following messages in the log due to not having the tofu-controller running in my cluster.

```
time="2024-10-01T19:55:32Z" level=info msg="Starting gitrepositories.source.toolkit.fluxcd.io controller"                                                                                                                           
time="2024-10-01T19:55:32Z" level=info msg="Starting ocirepositories.source.toolkit.fluxcd.io controller"                                                                                                                           
time="2024-10-01T19:55:32Z" level=info msg="Starting buckets.source.toolkit.fluxcd.io controller"                                                                                                                                   
time="2024-10-01T19:55:33Z" level=info msg="Starting helmrepositories.source.toolkit.fluxcd.io controller"                                                                                                                          
time="2024-10-01T19:55:34Z" level=info msg="Starting helmcharts.source.toolkit.fluxcd.io controller"                                                                                                                                
time="2024-10-01T19:55:34Z" level=info msg="Starting kustomizations.kustomize.toolkit.fluxcd.io controller"                                                                                                                         
time="2024-10-01T19:55:35Z" level=info msg="Starting helmreleases.helm.toolkit.fluxcd.io controller"                                                                                                                                
time="2024-10-01T19:55:35Z" level=info msg="Starting event controller"                                                                                                                                                              
time="2024-10-01T19:55:35Z" level=info msg="Starting deployment controller"                                                                                                                                                         
time="2024-10-01T19:55:35Z" level=info msg="Starting pod controller"                                                                                                                                                                
time="2024-10-01T19:55:35Z" level=info msg="Starting service controller"                                                                                                                                                            
time="2024-10-01T19:55:35Z" level=info msg="Starting ingress controller"                                                                                                                                                            
time="2024-10-01T19:55:35Z" level=warning msg="terraforms.infra.contrib.fluxcd.io is not supported on this cluster: the server could not find the requested resource"                                                               
time="2024-10-01T19:55:35Z" level=info msg=Initialized                                                                                                                                                                              
time="2024-10-01T19:55:36Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:55:36Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:55:41Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:55:41Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:55:41Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:55:41Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:55:49Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:55:49Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:55:49Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:55:49Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:56:03Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:56:03Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:56:03Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:56:04Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:56:04Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:56:05Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:56:05Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:56:44Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:56:44Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:56:44Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:56:44Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:56:53Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:56:53Z" level=warning msg="could not marshal event: the server could not find the requested resource"                                                                                                           
time="2024-10-01T19:56:53Z" level=warning msg="could not marshal event: the server could not find the requested resource"
...
```

Is there a chance to get the tofu-controller feature maybe on a feature flag?

**Comment by SvenW** [comment]
I noticed the same thing. Sorry for that. I've added a PR to fix the rbac issues but enabling/disabling the controller should maybe be configured via the env somehow

**Comment by SvenW** [comment]
@laszlocph Do you want me to just add the controller behind an env var or do you have a plan for enabling disabling controllers via something else?

**Comment by laszlocph** [comment]
v0.4.5 has the fix

flux reconcile source oci capacitor should pull it right in.

**Pull request merged**
