### PR TITLE
Publish OCI artifacts for Flux to continuously deploy Capacitor

### PR DESCRIPTION
**Pull request by stefanprodan**
This PR adds a step to the release workflow to push the install manifests to GHCR. From there, Flux running on clusters can install Capacitor using a Flux `OCIRepository` and Flux `Kustomization`. The readme contains the instructions on how to setup  continuously deployment for Capacitor with Flux.

### CODE REVIEW

**Comment by stefanprodan** [comment]
@laszlocph before you merges this, I would like to test the deployment using GHCR. Please run the following commands to have the artifact published:

```
git checkout capacitor-v0.1.0-rc.4

flux push artifact \
oci://ghcr.io/gimlet-io/capacitor-manifests:0.1.0-rc.4 \
--path=deploy/k8s \
--source=https://github.com/gimlet-io/capacitor \
--revision=v0.1.0-rc.4 \
--annotations='org.opencontainers.image.description=Capacitor install manifests for Flux'
```

**Comment by laszlocph** [comment]
Pushed: https://github.com/gimlet-io/capacitor/pkgs/container/capacitor-manifests/175386088?tag=v0.1.0-rc.4

**Comment by stefanprodan** [comment]
I tested it, it works from a Flux perspective, but Capacitor has no support for `OCIRepository` source type and the JS crashes. This PR can be merged only after the UI has support for this.

**Comment by laszlocph** [comment]
Just merged `OCIRepository` support. Merging this PR shortly.

**Pull request merged**
